[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache_path = "cache"

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM settings
evm_version = "paris"

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@chainlink/contracts/=node_modules/@chainlink/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Fuzz testing (CORRECTED - these are the right names)
[fuzz]
runs = 256
max_test_rejects = 65536

# Invariant testing
[invariant]
runs = 256
depth = 15
fail_on_revert = false

# Formatter
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

# RPC endpoints (optional - add your keys to .env)
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# Etherscan API keys (optional - add to .env)
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }