[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
monad = "${MONAD_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
monad = { key = "${MONAD_ETHERSCAN_API_KEY}", url = "https://explorer.monad.xyz/api" } # Example URL, replace with actual Monad explorer API
base = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }

# For keystore deployment, ensure your Foundry environment is configured to use it.
# Example environment variables for keystore:
# MONAD_KEYSTORE_PATH=/path/to/monad/keystore.json
# MONAD_KEYSTORE_PASSWORD=your_password
# BASE_KEYSTORE_PATH=/path/to/base/keystore.json
# BASE_KEYSTORE_PASSWORD=your_password

# Alternatively, for private key deployment:
# MONAD_PRIVATE_KEY=0x...
# BASE_PRIVATE_KEY=0x...