[profile.default]
src = 'src'
out = 'out'
libs = ["lib"]
include_paths = ["lib"]
remappings = [
    "forge-std=lib/forge-std/src/",
    "openzeppelin-contracts=lib/openzeppelin-contracts/",
]

[rpc_endpoints]
monad = "https://testnet-rpc.monad.xyz"

[etherscan]
monad = { key = "${ETHERSCAN_API_KEY}", url = "https://sourcify-api-monad.blockvision.org/api", chain = 10143 }